import { ArrowRight, BriefcaseBusiness, CheckCircle2 } from "lucide-react";
import Link from "next/link";
import SiteHeader from "@/components/layout/SiteHeader";

export const metadata = { title: "Careers", description: "Career opportunities and professional values at Capwise Solution BD.", alternates: { canonical: "/careers" } };

export default function CareersPage() {
  return <><SiteHeader/><main id="main-content">
    <section className="border-b border-border bg-background py-section-lg"><div className="mx-auto grid max-w-[94rem] gap-10 px-gutter lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="text-[.62rem] font-extrabold uppercase tracking-[.2em] text-brand-blue">Careers</p><h1 className="mt-5 max-w-[11ch] font-display text-h1 font-semibold text-foreground">Do careful work that businesses can rely on.</h1></div><div className="lg:col-span-4"><p className="text-base leading-8 text-muted">Capwise values clear thinking, accurate work, respectful communication and practical advice across finance, tax, legal and compliance assignments.</p></div></div></section>
    <section className="bg-surface py-section-md"><div className="mx-auto grid max-w-[94rem] gap-6 px-gutter lg:grid-cols-12"><div className="rounded-[1.5rem] bg-brand-navy p-8 text-white lg:col-span-7 sm:p-10"><BriefcaseBusiness className="text-brand-gold"/><p className="mt-8 text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-gold">Current openings</p><h2 className="mt-3 font-display text-h3 font-semibold">There are currently no advertised vacancies.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/64">When roles are formally approved, they will be published here with the scope, requirements and application process.</p></div><div className="rounded-[1.5rem] border border-border bg-background p-8 lg:col-span-5 sm:p-10"><p className="text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-blue">How we work</p><div className="mt-6 grid gap-4">{["Accuracy before speed","Simple communication","Professional confidentiality","Clear ownership of next steps"].map(item=><p key={item} className="flex items-center gap-3 border-t border-border pt-4 text-sm font-semibold text-foreground"><CheckCircle2 size={17} className="text-brand-gold"/>{item}</p>)}</div><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-brand-blue">Contact Capwise <ArrowRight size={15} className="text-brand-gold"/></Link></div></div></section>
  </main></>;
}
