import { ArrowRight, BriefcaseBusiness, CheckCircle2 } from "lucide-react";
import Link from "next/link";
import SiteHeader from "@/components/layout/SiteHeader";

export const metadata = { title: "Careers", description: "Career opportunities and professional values at Capwise Solution BD.", alternates: { canonical: "/careers" } };

export default function CareersPage() {
  return <><SiteHeader/><main id="main-content">
    <section className="border-b border-border bg-background py-section-lg"><div className="mx-auto grid max-w-[94rem] gap-10 px-gutter lg:grid-cols-12 lg:gap-14"><div className="lg:col-span-7"><p className="text-[.62rem] font-extrabold uppercase tracking-[.2em] text-brand-blue">Careers</p><h1 className="mt-5 max-w-[18ch] font-display text-h1 font-semibold text-foreground">Do careful work that businesses can rely on.</h1><p className="mt-6 max-w-xl text-base leading-8 text-muted">Capwise values clear thinking, accurate work, respectful communication and practical advice across finance, tax, legal and compliance assignments.</p><Link href="/contact" className="mt-8 inline-flex h-12 items-center gap-3 rounded-full bg-action px-6 text-sm font-bold text-action-foreground transition hover:-translate-y-0.5 hover:bg-action-hover">Contact Capwise <ArrowRight aria-hidden="true" size={17} /></Link></div><div className="lg:col-span-5"><div className="rounded-[1.5rem] border border-border bg-surface p-7 sm:p-8"><p className="text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-blue">How we work</p><div className="mt-5 grid gap-4">{["Accuracy before speed","Simple communication","Professional confidentiality","Clear ownership of next steps"].map(item=><p key={item} className="flex items-center gap-3 border-t border-border pt-4 text-sm font-semibold text-foreground"><CheckCircle2 size={17} className="text-brand-gold"/>{item}</p>)}</div></div></div></div></section>
    <section className="bg-surface py-section-md"><div className="mx-auto max-w-[94rem] px-gutter"><div className="rounded-[1.5rem] bg-brand-navy p-8 text-white sm:p-10"><BriefcaseBusiness className="text-brand-gold"/><p className="mt-8 text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-gold">Current openings</p><h2 className="mt-3 font-display text-h3 font-semibold">There are currently no advertised vacancies.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/64">When roles are formally approved, they will be published here with the scope, requirements and application process.</p></div></div></section>
  </main></>;
}
