import { ArrowRight, Check, MessageCircle } from "lucide-react";
import Link from "next/link";
import SiteHeader from "@/components/layout/SiteHeader";
import { primaryContact, whatsappHref } from "@/config/contacts";
import { featuredTeamMembers, supportingTeamMembers, TEAM_CONTENT_VERSION } from "@/data/team";

export const metadata = { title:"Our Team", description:"Meet the multidisciplinary financial, tax, audit, legal and regulatory advisory team at Capwise Solution BD.", alternates:{canonical:"/team"} };

function ProfileCard({ member, featured=false, index }) {
  return <article id={member.slug} className={`scroll-mt-28 rounded-[1.5rem] ${featured?"bg-brand-navy text-white shadow-[0_28px_80px_rgba(27,20,100,.16)]":"border border-border bg-surface text-foreground"} p-7 sm:p-9`}>
    <div className="flex items-start justify-between gap-5"><span className={`inline-flex ${featured?"size-20 border-white/15 bg-white/7 text-white":"size-16 border-brand-blue/20 bg-brand-blue/8 text-brand-blue"} items-center justify-center rounded-full border font-display text-lg font-extrabold`}>{member.initials}</span><span className={`text-xs font-extrabold ${featured?"text-brand-gold":"text-muted/45"}`}>{String(index+1).padStart(2,"0")}</span></div>
    <p className={`mt-8 text-[.6rem] font-extrabold uppercase tracking-[.17em] ${featured?"text-brand-gold":"text-brand-blue"}`}>{member.role}</p>
    <h2 className={`mt-3 font-display ${featured?"text-card":"text-lg"} font-semibold leading-[1.1] tracking-[-0.02em]`}>{member.name}</h2>
    <p className={`mt-4 text-sm leading-7 ${featured?"text-white/64":"text-muted"}`}>{member.specialty}</p>
    <p className={`mt-6 border-t pt-5 text-sm leading-7 ${featured?"border-white/12 text-white/62":"border-border text-muted"}`}>{member.summary}</p>
    <div className="mt-6 grid gap-2 sm:grid-cols-2">{[member.experience,member.credential].map(item=><div key={item} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-[.68rem] font-bold ${featured?"border-white/10 bg-white/[.04] text-white/65":"border-border bg-background text-muted"}`}><Check size={13} className={featured?"text-brand-gold":"text-brand-blue"}/>{item}</div>)}</div>
  </article>;
}

export default function TeamPage(){return <><SiteHeader/><main id="main-content" data-team-version={TEAM_CONTENT_VERSION}>
  <section className="border-b border-border bg-background py-section-lg"><div className="mx-auto grid max-w-[94rem] gap-10 px-gutter lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="text-[.62rem] font-extrabold uppercase tracking-[.2em] text-brand-blue">Our Team</p><h1 className="mt-5 max-w-[12ch] font-display text-h1 font-semibold text-foreground">Different disciplines. One shared direction.</h1></div><div className="lg:col-span-4"><p className="text-base leading-8 text-muted">Finance, tax, audit, regulatory and legal perspectives are brought together around the client’s actual business issue.</p></div></div></section>
  <section className="bg-background py-section-md"><div className="mx-auto max-w-[94rem] px-gutter"><p className="text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-blue">Featured team members</p><div className="mt-6 grid gap-5 lg:grid-cols-2">{featuredTeamMembers.map((m,i)=><ProfileCard key={m.slug} member={m} featured index={i}/>)}</div><p className="mt-14 text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-blue">Supporting team</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{supportingTeamMembers.map((m,i)=><ProfileCard key={m.slug} member={m} index={i+featuredTeamMembers.length}/>)}</div></div></section>
  <section className="bg-brand-navy py-section-md text-white"><div className="mx-auto flex max-w-[94rem] flex-col gap-8 px-gutter lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[.6rem] font-extrabold uppercase tracking-[.18em] text-brand-gold">Start with context</p><h2 className="mt-3 max-w-3xl font-display text-h3 font-semibold">Bring the full business picture to one conversation.</h2></div><div className="flex flex-wrap gap-3"><Link href="/contact" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-brand-gold px-6 text-sm font-extrabold text-brand-navy shadow-[0_10px_28px_rgba(212,175,55,.2)] transition duration-200 hover:-translate-y-0.5 hover:bg-brand-gold-soft active:translate-y-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-brand-navy">Book a Free Consultation <ArrowRight size={16}/></Link><a href={whatsappHref(primaryContact.whatsapp, "Hello Capwise, I would like to book a consultation.")} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/18 px-6 text-sm font-bold"><MessageCircle size={16}/>WhatsApp</a></div></div></section>
</main></>}
